#!/bin/bash

b="/var/log/wtmp"
comanda="./authParse.sh"
fl=1
n=-1
s=""
t=""
p=""

while [[ $# > 0 ]]; do
    case $1 in
    -b)
        fl=0
        b="/var/log/btmp"
        shift
        ;;
    -c)
        comanda="./inputParse"
        shift
        ;;
    -n)
        shift
        if [[ $# == 0 ]]; then
            echo "Lipeste un parametru pentru limitarea numarului de linii afisate"
            exit 5
        fi
        n="$1"
        shift
        ;;
    -s)
        shift
        if [[ $# == 0 ]]; then
            echo "Lipeste un parametru pentru argumentul 'since'"
            exit 5
        fi
        s="$1"
        shift
        ;;
    -t) 
        shift
        if [[ $# == 0 ]]; then
            echo "Lipeste un parametru pentru argumentul 'until'"
            exit 5
        fi
        t="$1"
        shift
        ;;
    -p) 
        shift
        if [[ $# == 0 ]]; then
            echo "Lipeste un parametru pentru argumentul 'present'"
            exit 5
        fi
        p="$1"
        shift
        ;;
    *)
        echo "parametru necunoscut $1"
        exit 5
        ;;
    esac
done

transformare(){
    local data="$1" 
    date -d "$data" +%s

}

if [[ "$s" != "" ]]; then
    s=$(transformare "$s")
fi

if [[ "$t" != "" ]]; then
    t=$(transformare "$t")
fi

if [[ "$p" != "" ]]; then
    p=$(transformare "$p")
fi

cmd=( "$comanda" "$b" )

count=0
timp_prec=-1
"${cmd[@]}" | while IFS= read -r linie; do
    IFS=',' read -r f user line host timp durata <<< "$linie"
    if [[ $line == "~" ]]; then
        line="system boot"
        still_logged_in=0
    fi
    if [[ $fl == 1 && $f == 0 || $user == "" ]]; then
        continue
    fi
    if [[ "$s" != "" && $s -gt $timp ]]; then 
        exit 0
    fi
    if [[ "$t" != "" && $t < $timp ]]; then 
        continue
    fi
    if [[ "$p" != "" && "$timp" -ne "$p" ]]; then
        continue
    fi
    ((count++))
    if [[ "$n" -ge 0 && "$count" -gt "$n" ]]; then
        exit 0
    fi
    durata=$((timp_prec-timp))
    durata=$(printf "%d:%02d:%02d" $((durata / 3600)) $((durata / 60 % 60)) $((durata % 60)))
    if [[ $still_logged_in == 1 ]]; then
        durata=$(printf "still logged in %s" "$durata")
    fi
    timp=$(date -d "@$timp" +"%d.%m.%y %H:%M")
    printf "%-10s | %-12s | %-15s | %-10s | %-10s\n" "$user" "$line" "$host" "$timp" "$durata" 
done